function processGrammar() {
    const input = document.getElementById('grammar-input').value;
    const vizContainer = document.getElementById('visualization');
    vizContainer.innerHTML = ''; // Clear previous runs

    try {
        let grammar = parseInput(input);
        displayStep(vizContainer, "Original Grammar", grammar, "Starting point of our grammar.");

        grammar = eliminateNull(grammar);
        displayStep(vizContainer, "Step 1: Eliminate Null (ε) Productions", grammar, "Removed productions generating 'e' and added compensations.");

        grammar = eliminateUnit(grammar);
        displayStep(vizContainer, "Step 2: Eliminate Unit Productions", grammar, "Removed rules like A -> B, substituting B's RHS into A.");

        grammar = eliminateUseless(grammar);
        displayStep(vizContainer, "Step 3: Eliminate Useless Symbols", grammar, "Removed non-generating and unreachable symbols.");
    } catch (err) {
        // If anything crashes, show it on the screen instead of failing silently
        vizContainer.innerHTML = `<div style="color:red; background:#fee2e2; padding:20px; border-radius:8px; border:1px solid #ef4444;">
            <strong>Execution Error:</strong> ${err.message}. <br>Please check your grammar format or developer console.
        </div>`;
        console.error(err);
    }
}

function parseInput(text) {
    const lines = text.split('\n');
    let grammar = {};
    lines.forEach(line => {
        if (!line.includes('->')) return;
        let [lhs, rhs] = line.split('->').map(s => s.trim());
        if (!lhs || !rhs) return; // Safeguard against empty lines
        if (!grammar[lhs]) grammar[lhs] = [];
        let productions = rhs.split('|').map(s => s.trim());
        grammar[lhs].push(...productions);
    });
    return grammar;
}

function displayStep(container, title, grammar, explanation) {
    const stepDiv = document.createElement('div');
    stepDiv.className = 'step-card';
    
    let grammarText = '';
    for (const [lhs, rhsArr] of Object.entries(grammar)) {
        const uniqueRhs = [...new Set(rhsArr)].filter(r => r !== '');
        if (uniqueRhs.length > 0) {
            grammarText += `${lhs} -> ${uniqueRhs.join(' | ')}\n`;
        }
    }

    stepDiv.innerHTML = `
        <h2>${title}</h2>
        <p class="explanation">${explanation}</p>
        <div class="grammar-display">${grammarText || "Empty Grammar"}</div>
    `;
    container.appendChild(stepDiv);
}

// --- ACTUAL ALGORITHM IMPLEMENTATIONS ---

// Helper function to check if a character is a Non-Terminal (Variable)
function isVariable(char) {
    return char.length === 1 && char >= 'A' && char <= 'Z';
}

// STEP 1: ELIMINATE NULL (ε) PRODUCTIONS
function eliminateNull(grammar) {
    let nullables = new Set();
    let changed = true;

    // Phase A: Find all nullable variables
    while (changed) {
        changed = false;
        for (let lhs in grammar) {
            if (!nullables.has(lhs)) {
                for (let rhs of grammar[lhs]) {
                    if (rhs === 'e') {
                        nullables.add(lhs);
                        changed = true;
                        break;
                    } else {
                        let allNullable = true;
                        let hasVariables = false;
                        for (let char of rhs) {
                            if (char === ' ') continue; // Ignore spaces
                            hasVariables = true;
                            if (!nullables.has(char)) {
                                allNullable = false;
                                break;
                            }
                        }
                        if (hasVariables && allNullable) {
                            nullables.add(lhs);
                            changed = true;
                            break;
                        }
                    }
                }
            }
        }
    }

    // Phase B: Generate power sets for productions containing nullable variables
    let newGrammar = {};
    for (let lhs in grammar) {
        let newRhs = new Set();
        for (let rhs of grammar[lhs]) {
            if (rhs === 'e') continue; // Drop the explicit nulls
            
            let combinations = getNullCombinations(rhs, nullables);
            combinations.forEach(comb => {
                // Clean up any double spaces or trailing spaces generated by removing variables
                let cleaned = comb.replace(/\s+/g, ' ').trim(); 
                if (cleaned !== '') newRhs.add(cleaned);
            });
        }
        if (newRhs.size > 0) newGrammar[lhs] = Array.from(newRhs);
    }
    return newGrammar;
}

// Recursive helper to generate combinations for nullable variables
function getNullCombinations(str, nullables) {
    let results = [''];
    for (let char of str) {
        let nextResults = [];
        for (let res of results) {
            nextResults.push(res + char); // Keep the character
            if (nullables.has(char)) {
                nextResults.push(res); // Drop the character if it's nullable
            }
        }
        results = nextResults;
    }
    return results;
}

// STEP 2: ELIMINATE UNIT PRODUCTIONS
function eliminateUnit(grammar) {
    let newGrammar = {};
    
    for (let lhs in grammar) {
        let reachable = new Set([lhs]);
        let queue = [lhs]; // For Breadth-First Search (BFS)
        
        // Phase A: Find all variables reachable via unit productions
        while (queue.length > 0) {
            let current = queue.shift();
            if (grammar[current]) {
                for (let rhs of grammar[current]) {
                    if (rhs.length === 1 && isVariable(rhs)) {
                        if (!reachable.has(rhs)) {
                            reachable.add(rhs);
                            queue.push(rhs);
                        }
                    }
                }
            }
        }
        
        // Phase B: Substitute terminal rules back to the LHS
        let newRhs = new Set();
        for (let target of reachable) {
            if (grammar[target]) {
                for (let rhs of grammar[target]) {
                    if (!(rhs.length === 1 && isVariable(rhs))) { // Only add non-unit rules
                        newRhs.add(rhs);
                    }
                }
            }
        }
        if (newRhs.size > 0) newGrammar[lhs] = Array.from(newRhs);
    }
    return newGrammar;
}

// STEP 3: ELIMINATE USELESS SYMBOLS
function eliminateUseless(grammar) {
    // Phase 1: Remove Non-Generating Symbols (Bottom-Up)
    let generating = new Set();
    let changed = true;
    
    while (changed) {
        changed = false;
        for (let lhs in grammar) {
            if (!generating.has(lhs)) {
                for (let rhs of grammar[lhs]) {
                    let isGen = true;
                    for (let char of rhs) {
                        if (char === ' ') continue; // Ignore spaces
                        if (isVariable(char) && !generating.has(char)) {
                            isGen = false; 
                            break;
                        }
                    }
                    if (isGen) {
                        generating.add(lhs); 
                        changed = true; 
                        break;
                    }
                }
            }
        }
    }

    // Create intermediate grammar with only generating symbols
    let genGrammar = {};
    for (let lhs in grammar) {
        if (generating.has(lhs)) {
            let newRhs = [];
            for (let rhs of grammar[lhs]) {
                let valid = true;
                for (let char of rhs) {
                    if (char === ' ') continue; // Ignore spaces
                    if (isVariable(char) && !generating.has(char)) valid = false;
                }
                if (valid) newRhs.push(rhs);
            }
            if (newRhs.length > 0) genGrammar[lhs] = newRhs;
        }
    }

    // Phase 2: Remove Unreachable Symbols (Top-Down from Start Symbol)
    let startSymbol = Object.keys(genGrammar)[0]; // Assumes first rule is Start symbol
    if (!startSymbol) return {}; // Grammar is empty
    
    let reachable = new Set([startSymbol]);
    let queue = [startSymbol]; 
    
    while (queue.length > 0) {
        let current = queue.shift();
        if (genGrammar[current]) {
            for (let rhs of genGrammar[current]) {
                for (let char of rhs) {
                    if (isVariable(char)) {
                        if (!reachable.has(char)) {
                            reachable.add(char);
                            queue.push(char);
                        }
                    }
                }
            }
        }
    }

    // Final filter: keep only rules that are BOTH generating and reachable
    let finalGrammar = {};
    for (let lhs in genGrammar) {
        if (reachable.has(lhs)) {
            finalGrammar[lhs] = genGrammar[lhs];
        }
    }
    
    return finalGrammar;
}